### PR TITLE
fetching auth JSON file in better way and send multiple FCM tokens

### PR DESCRIPTION
**Pull request by detailsSA**
it's not secure storing auth file inside storage directory besides we can't push the auth file to the production servers because storage directory is always ignored

### CODE REVIEW

**Comment by paxha** [comment]
Can you please give any example for wiki that how can i set my path for service account?

**Comment by detailsSA** [comment]
> Can you please give any example for wiki that how can i set my path for service account?

config/fcm.php

'service_account' => env('GOOGLE_SERVICE_ACCOUNT', __DIR__ . '/fcmCertificates/xxx-firebase-adminsdk-xxx-xxxxxxxx.json'),

**Comment by paxha** [comment]
ok, have you tested this code? include single and multiple tokens?

**Comment by paxha** [comment]
Screenshot 2024-05-23 at 20 51 10
please review this. is it okay? will it work ?

**Comment by detailsSA** [comment]
> ok, have you tested this code? include single and multiple tokens?

yes, it's tested and gone to our production.

> Screenshot 2024-05-23 at 20 51 10 please review this. is it okay? will it work ?

I think it's better to store the auth file inside config directory not root or you have to change

`'service_account' => env('GOOGLE_SERVICE_ACCOUNT')`

with

`'service_account' => base_path(env('GOOGLE_SERVICE_ACCOUNT'))`

or this for config

`'service_account' => config_path(env('GOOGLE_SERVICE_ACCOUNT'))`

**Comment by paxha** [comment]
3.0 tag is created. You can test it.

**Pull request merged**
